// D4 v2 AVOIDANCE GATE — auto-generated by scripts/d4_v2_avoidance.py
// Phase F analysis-only artifact. Deterministic, no new deps.
// TRADE if P(WIN) >= TAU, else SKIP (avoid).
// Coefficients from ridge logistic regression on TRAIN (08-01..08-06),
// standardized numeric + one-hot categorical. Holdout-evaluated, NOT live.
export const D4V2_GATE = Object.freeze({
  TAU: 0.507293,
  B0: -0.760300,
  NUM: {
    confidence: { w: 0.010378, mean: 82.000000, std: 7.162987 },
    coreConfidence: { w: -0.030864, mean: 96.000000, std: 6.578092 },
    hour: { w: -0.102590, mean: 11.000000, std: 6.845019 },
    dow: { w: 0.047276, mean: 2.000000, std: 1.770475 },
  },
  CAT: {
    pair: { "ADA/USD": -0.070880, "AUD/USD": -0.063432, "AVAX/USD": -0.102624, "BNB/USD": 0.007308, "BTC/USD": -0.156275, "DOGE/USD": 0.066013, "DOT/USD": -0.044613, "ETH/USD": -0.054120, "EUR/USD": -0.212328, "GBP/USD": -0.354648, "LINK/USD": 0.145545, "SOL/USD": 0.124777, "USD/JPY": 0.287854, "XRP/USD": 0.259233 },
    assetType: { "CRYPTO": 0.174363, "FOREX": -0.342554 },
    direction: { "BUY": -0.125797, "SELL": -0.042394 },
    bestTF: { "15min": -0.041165, "1min": -0.137204, "5min": 0.010178 },
    marketRegime: { "BREAKOUT": 0.316759, "RANGING": 0.009285, "TRENDING": 0.323450, "VOLATILE": -0.817685 },
    sessionQuality: { "HIGH": 0.239319, "HIGHEST": -0.093080, "LOW": -0.238844, "MEDIUM": -0.249949, "N/A": 0.174363 },
    grade: { "A": -0.081700, "A+": -0.200563, "B": 0.028977, "C": 0.085095 },
    alignment: { "ALL_BEARISH": 0.341013, "ALL_BULLISH": 0.226842, "MOSTLY_BEARISH": -0.383407, "MOSTLY_BULLISH": -0.352639 },
    structureVerdict: { "AGAINST": 0.085095, "ALIGNED": -0.003825, "MIXED": -0.149767, "NEUTRAL": -0.099694 },
  },
});

// Apply per signal (all inputs known at signal time):
//   z = D4V2_GATE.B0
//     + (confidence-1)*0 ... see NUM mapping; + CAT lookups (0/1)
export function d4v2Avoid(p) {
  const G = D4V2_GATE;
  let z = G.B0;
  for (const n of ['confidence','coreConfidence','hour','dow']) {
    const v = p[n] == null ? G.NUM[n].mean : p[n];
    z += G.NUM[n].w * (v - G.NUM[n].mean) / G.NUM[n].std;
  }
  for (const c of Object.keys(G.CAT)) {
    const lvl = p[c];
    if (lvl != null && G.CAT[c][lvl] !== undefined) z += G.CAT[c][lvl];
  }
  const pWin = 1 / (1 + Math.exp(-z));
  return { trade: pWin >= G.TAU, pWin };
}
