/**
 * Phase 10 — cross-surface signal push.
 *
 * When a fresh BUY/SELL signal is generated by ANY caller (App view, Bot
 * command, Bot autoScan), matching Telegram subscribers are notified straight
 * from the worker — no cache, no polling, sub-second delivery.
 *
 * ── Design decisions, all driven by live inspection of the Bot repo ─────────
 *
 * 1. Subscriber enumeration uses the Bot's OWN index (`auto_users`), not a
 *    `BOT_KV.list({prefix:'u:'})` scan. The Bot maintains that array itself
 *    (getAutoUsers/addAutoUser) and its cron reads exactly it, so we see the
 *    same population the Bot does — and pay 1 + N reads instead of a full
 *    keyspace list on every signal.
 *
 * 2. Filter semantics are copied from the Bot's own passGrade/passConf/passAI
 *    helpers, NOT from the rank-table in the Phase 10 spec. The Bot only ever
 *    stores gradeFilter values 'ALL' | 'AB' | 'A' (settings keyboard line 606);
 *    a numeric A+/A/B/C/D ranking would mis-filter every subscriber.
 *
 * 3. Messages are sent as PLAIN TEXT with no parse_mode. The Bot deliberately
 *    removed parse_mode after its Bug#1: signal text contains ( ) . ! - _ which
 *    made Telegram reject MarkdownV2 with HTTP 400 while the error was only
 *    logged, so users silently got nothing. The spec's `parse_mode:'HTML'`
 *    would reintroduce that class of failure (entryReason regularly contains
 *    '<' / '&' style characters). See PHASE_10_REPORT.md §1.3.
 *
 * 4. A per-signal push-lock makes the push idempotent. /api/signal is called
 *    constantly (App auto-refresh is 60s post-revert, Bot cron every 5min, plus
 *    every manual view), and each call mints a NEW signalId even when the
 *    worker's own 30-minute dedup guard treats it as a re-poll. Without a lock
 *    one setup would be pushed dozens of times. See §1.4.
 */



const PUSH_LOG_PREFIX  = 'pushLog:';    // pushLog:<signalId> -> [{chatId, sentAt}]
const PUSH_LOCK_PREFIX = 'pushLock:';   // pushLock:<chatId>:<PAIR>:<DIR> -> signalId
const PUSH_LOG_TTL_S   = 24 * 3600;
/**
 * How long one (subscriber, pair, direction) stays muted after a push.
 * Mirrors the worker's own DEDUP_WINDOW_MS (30 min) so a push happens exactly
 * when a genuinely new setup is recorded in history, not on every re-poll.
 */
const PUSH_LOCK_TTL_S  = 30 * 60;

// Durable diagnostics — survive result-push deleting pushLog:<id>.
const LAST_ATTEMPT_KEY   = 'push:lastAttempt';
const DELIVERED_24H_KEY  = 'push:delivered24h';
const TOKEN_CHECK_KEY    = 'push:tokenCheck';
const TOKEN_CHECK_TTL_S  = 300;

const TELEGRAM_API = 'https://api.telegram.org';
const SELF_URL = 'https://fttotcv6.umuhammadiswa.workers.dev';

/** Trim so a dashboard paste with trailing newline is not a silent 401. */
export function botToken(env) {
  return env && env.BOT_TOKEN ? String(env.BOT_TOKEN).trim() : '';
}

/** Bot stores pairs slash-less ("EURUSD"); normalise both sides before compare. */
function normPair(p) {
  return String(p || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
}

function confPct(sig) {
  return parseInt(String((sig && sig.confidence) || '0%').replace('%', ''), 10) || 0;
}

/**
 * Coerce the Bot's `auto_users` index into chat-id strings.
 * Live shape is `["123456"]`, but a dashboard edit or an older writer can
 * leave numbers, `u:<id>` keys, or `{chatId}` objects — all of which made
 * `u:` + cid look up the wrong KV key and silently match nobody.
 */
export function normalizeAutoUsers(raw) {
  if (!Array.isArray(raw)) return [];
  const ids = [];
  for (const entry of raw) {
    if (entry == null) continue;
    if (typeof entry === 'number' && isFinite(entry)) {
      ids.push(String(Math.trunc(entry)));
      continue;
    }
    if (typeof entry === 'string') {
      const s = entry.trim();
      if (!s) continue;
      ids.push(s.startsWith('u:') ? s.slice(2) : s);
      continue;
    }
    if (typeof entry === 'object') {
      const v = entry.chatId ?? entry.id ?? entry.cid ?? entry.chat_id;
      if (v == null) continue;
      const s = String(v).trim();
      if (s) ids.push(s.startsWith('u:') ? s.slice(2) : s);
    }
  }
  return ids;
}

/** Accept boolean true plus the string/number forms a KV edit can leave. */
export function isAutoEnabled(user) {
  if (!user) return false;
  return user.autoEnabled === true || user.autoEnabled === 1 || user.autoEnabled === 'true';
}

function lockKey(chatId, signal) {
  return PUSH_LOCK_PREFIX + chatId + ':' + normPair(signal.pair)
    + ':' + signal.signal.finalSignal;
}

async function releasePushLock(chatId, signal, env) {
  if (!env || !env.SIGNAL_CACHE) return;
  try { await env.SIGNAL_CACHE.delete(lockKey(chatId, signal)); }
  catch (e) { console.warn('push: lock release failed: ' + e.message); }
}

async function recordPushAttempt(env, rec) {
  if (!env || !env.SIGNAL_CACHE) return;
  try {
    await env.SIGNAL_CACHE.put(
      LAST_ATTEMPT_KEY,
      JSON.stringify({ ...rec, at: new Date().toISOString() }),
      { expirationTtl: 7 * 24 * 3600 },
    );
  } catch (e) {
    console.warn('push: lastAttempt write failed: ' + e.message);
  }
}

async function recordDelivery(env, signalId, pair, n) {
  if (!env || !env.SIGNAL_CACHE || !n) return;
  try {
    let arr = await env.SIGNAL_CACHE.get(DELIVERED_24H_KEY, 'json');
    if (!Array.isArray(arr)) arr = [];
    const now = Date.now();
    arr = arr.filter(x => x && x.at && (now - new Date(x.at).getTime()) < 24 * 3600 * 1000);
    arr.push({ id: signalId, pair, n, at: new Date().toISOString() });
    if (arr.length > 500) arr = arr.slice(-500);
    await env.SIGNAL_CACHE.put(DELIVERED_24H_KEY, JSON.stringify(arr), { expirationTtl: 48 * 3600 });
  } catch (e) {
    console.warn('push: delivered24h write failed: ' + e.message);
  }
}

// ── filter helpers — mirrored from the Bot's own implementation ─────────
export function passGrade(sig, f) {
  if (!f || f === 'ALL') return true;
  const g = (sig && sig.grade && sig.grade.grade) || '';
  if (!g) return false;
  // F3-03 (BUG-026): an 'A+' signal must satisfy 'A' and 'AB' filters — the
  // top-tier grade is a strict superset of A. Exact equality previously
  // dropped every A+ signal for A/AB-filtered subscribers.
  return f === 'A' ? ['A+', 'A'].includes(g) : f === 'AB' ? ['A+', 'A', 'B'].includes(g) : true;
}

export function passConf(sig, min) {
  if (!min) return true;
  return confPct(sig) >= min;
}

export function passAI(sig, aiOnly) {
  if (!aiOnly) return true;
  if (!sig || !sig.aiValidation) return false;
  const v = sig.aiValidation;
  // Bugfix round 1 (CHECK-A / BUG-006): the standard engine REPLACES
  // aiValidation with the dual-combiner object `{cerebras, groq, combined,
  // combinedAgreed}` (combine.js) — there is no top-level `status` field, so
  // the old check `v.status === 'OK'` was always false and aiOnly subscribers
  // could never match. Accept both shapes: OTC leaves `{status, agrees}`,
  // standard leaves `{combined.status, combinedAgreed/agrees}`.
  const status = v.status || (v.combined && v.combined.status);
  const agreed = v.agrees !== undefined ? v.agrees : v.combinedAgreed;
  return status === 'OK' && agreed === true;
}

/**
 * Everyone who should receive this signal.
 * Returns [{ chatId, channelId }] — channelId mirrors the Bot's [F10] behaviour.
 * Optional `diag.skips` is filled with per-subscriber skip reasons so /health
 * can show WHY a live signal matched nobody (the previous silent `no-match`).
 */
export async function getMatchingSubscribers(signal, env, diag = null) {
  if (diag && !Array.isArray(diag.skips)) diag.skips = [];
  if (!env || !env.BOT_KV) {
    if (diag) diag.skips.push({ reason: 'no-bot-kv' });
    return [];
  }
  const sig = signal && signal.signal;
  if (!sig) {
    if (diag) diag.skips.push({ reason: 'no-signal' });
    return [];
  }

  let autoUsers;
  try {
    autoUsers = await env.BOT_KV.get('auto_users', 'json');
  } catch (e) {
    console.warn('push: auto_users read failed: ' + e.message);
    if (diag) diag.skips.push({ reason: 'auto-users-read-failed', error: e.message });
    return [];
  }
  const ids = normalizeAutoUsers(autoUsers);
  if (diag) {
    diag.autoUsersRawType = Array.isArray(autoUsers) ? 'array' : typeof autoUsers;
    diag.autoUsersCount = ids.length;
  }
  if (ids.length === 0) {
    if (diag) diag.skips.push({ reason: 'auto-users-empty' });
    return [];
  }

  const want = normPair(signal.pair);
  const matches = [];

  for (const cid of ids) {
    try {
      const user = await env.BOT_KV.get('u:' + cid, 'json');
      if (!user) {
        if (diag) diag.skips.push({ chatId: String(cid), reason: 'no-user-record' });
        continue;
      }
      if (!isAutoEnabled(user)) {
        if (diag) diag.skips.push({ chatId: String(cid), reason: 'auto-disabled' });
        continue;
      }

      const watched = [user.pair, ...(Array.isArray(user.watchlist) ? user.watchlist : [])]
        .filter(Boolean)
        .map(normPair);
      if (!watched.includes(want)) {
        if (diag) diag.skips.push({
          chatId: String(cid), reason: 'pair-not-watched',
          want, pair: user.pair || null,
          watchlist: Array.isArray(user.watchlist) ? user.watchlist : [],
        });
        continue;
      }

      // Same three gates the Bot applies in autoScan.
      if (!passConf(sig, user.minConfidence)) {
        if (diag) diag.skips.push({ chatId: String(cid), reason: 'min-confidence', min: user.minConfidence });
        continue;
      }
      if (!passGrade(sig, user.gradeFilter)) {
        if (diag) diag.skips.push({ chatId: String(cid), reason: 'grade-filter', filter: user.gradeFilter });
        continue;
      }
      if (!passAI(sig, user.aiOnlyMode)) {
        if (diag) diag.skips.push({ chatId: String(cid), reason: 'ai-only' });
        continue;
      }

      matches.push({ chatId: String(cid), channelId: user.channelId || null, fxMode: user.fxMode || 'ftt' });
    } catch (e) {
      console.warn('push: user read failed for ' + cid + ': ' + e.message);
      if (diag) diag.skips.push({ chatId: String(cid), reason: 'user-read-failed', error: e.message });
    }
  }
  return matches;
}

/**
 * Claim the right to push this (subscriber, pair, direction) combination.
 * Returns true only for the first caller inside the lock window.
 *
 * KV has no atomic compare-and-set, so a genuine race can let two concurrent
 * requests both claim. That is acceptable: the worst case is one duplicate
 * message, versus dozens without the lock.
 */
async function claimPushLock(chatId, signal, env) {
  if (!env.SIGNAL_CACHE) return true;
  const key = lockKey(chatId, signal);
  try {
    const held = await env.SIGNAL_CACHE.get(key);
    if (held) return false;
    await env.SIGNAL_CACHE.put(key, signal.id, { expirationTtl: PUSH_LOCK_TTL_S });
    return true;
  } catch (e) {
    // Never let lock bookkeeping suppress a signal.
    console.warn('push: lock check failed: ' + e.message);
    return true;
  }
}

/**
 * Push a fresh signal to every matching subscriber.
 * Call inside ctx.waitUntil() — never block the caller's response.
 */
export async function pushSignalToSubscribers(signal, env) {
  const diag = { skips: [] };
  const out = await pushSignalToSubscribersInner(signal, env, diag);
  await recordPushAttempt(env, {
    signalId: signal && signal.id || null,
    pair: signal && signal.pair || null,
    dir: signal && signal.signal && signal.signal.finalSignal || null,
    skipped: out.skipped || null,
    pushed: out.pushed || 0,
    matched: out.matched || 0,
    error: out.error || null,
    telegramError: out.telegramError || null,
    skips: diag.skips,
  });
  return out;
}

async function pushSignalToSubscribersInner(signal, env, diag) {
  if (!signal || !signal.id) return { pushed: 0, skipped: 'no-id' };
  const sig = signal.signal;
  if (!sig || !['BUY', 'SELL'].includes(sig.finalSignal)) {
    return { pushed: 0, skipped: 'not-actionable' };
  }
  if (!env || !botToken(env)) {
    return { pushed: 0, skipped: 'no-token' };
  }

  try {
    const subscribers = await getMatchingSubscribers(signal, env, diag);
    if (subscribers.length === 0) return { pushed: 0, skipped: 'no-match', matched: 0 };

    const eligible = [];
    for (const sub of subscribers) {
      if (await claimPushLock(sub.chatId, signal, env)) eligible.push(sub);
      else if (diag) diag.skips.push({ chatId: sub.chatId, reason: 'locked' });
    }
    if (eligible.length === 0) return { pushed: 0, skipped: 'locked', matched: subscribers.length };

    const results = await Promise.allSettled(
      eligible.map(async (sub) => {
        let msgSignal = signal;
        if ((sub.fxMode === 'fx' || sub.fxMode === 'both') && !signal.signal.fxLevels) {
          try {
            const fx = await fetch(`${SELF_URL}/api/signal?pair=${encodeURIComponent(signal.pair)}&mode=fx&nopush=1`,
              { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(8000) });
            if (fx.ok) {
              const fd = await fx.json();
              if (fd && fd.signal && fd.signal.fxLevels) msgSignal = fd;
            }
          } catch (e) { console.warn('push: fx fetch failed (fallback FTT): ' + e.message); }
        }
        const fxOnly = sub.fxMode === 'fx';
        const message = formatSignalMessage(msgSignal, { fx: sub.fxMode === 'fx' || sub.fxMode === 'both', fxOnly });
        try {
          await sendTelegramMessage(sub.chatId, message, env);
        } catch (e) {
          // Live 2026-08-12: lock was claimed BEFORE send. A 401/403 left the
          // lock held for 30 min and wrote no pushLog — next tick was 'locked',
          // /health.pushesLast24h stayed 0, user never got a retry.
          await releasePushLock(sub.chatId, signal, env);
          throw e;
        }
        return { sub, message };
      }),
    );

    const delivered = [];
    const telegramErrors = [];
    results.forEach((r) => {
      if (r.status === 'fulfilled' && r.value) delivered.push(r.value);
      else if (r.status === 'rejected') {
        telegramErrors.push(String((r.reason && r.reason.message) || r.reason || 'send-failed'));
      }
    });

    await Promise.allSettled(
      delivered.filter(d => d.sub.channelId)
        .map(d => sendTelegramMessage(d.sub.channelId, d.message, env)),
    );

    if (delivered.length > 0 && env.SIGNAL_CACHE) {
      const now = new Date().toISOString();
      await env.SIGNAL_CACHE.put(
        PUSH_LOG_PREFIX + signal.id,
        JSON.stringify(delivered.map(d => ({ chatId: d.sub.chatId, sentAt: now }))),
        { expirationTtl: PUSH_LOG_TTL_S },
      );
      await recordDelivery(env, signal.id, signal.pair, delivered.length);
    }

    console.log('Phase 10 push: ' + signal.id + ' ' + signal.pair + ' '
      + sig.finalSignal + ' -> ' + delivered.length + '/' + eligible.length
      + ' delivered (' + subscribers.length + ' matched)'
      + (telegramErrors.length ? ' telegramErrors=' + telegramErrors[0] : ''));
    const skipped = delivered.length === 0
      ? (telegramErrors.length ? 'telegram-fail' : 'no-delivery')
      : undefined;
    return {
      pushed: delivered.length,
      matched: subscribers.length,
      skipped,
      telegramError: telegramErrors[0] || null,
    };
  } catch (e) {
    console.warn('pushSignalToSubscribers error: ' + e.message);
    return { pushed: 0, error: e.message };
  }
}

/**
 * Result push — fired by the cron result checker when a signal resolves.
 * Only the subscribers who actually received the original signal are told.
 */
export async function pushResultToSubscribers(record, winLoss, exitPrice, env) {
  if (!record || !record.id) return { pushed: 0 };
  if (!['WIN', 'LOSS'].includes(winLoss)) return { pushed: 0, skipped: 'undecided' };
  if (!env || !botToken(env) || !env.SIGNAL_CACHE) return { pushed: 0, skipped: 'not-configured' };

  try {
    const logKey = PUSH_LOG_PREFIX + record.id;
    const log = await env.SIGNAL_CACHE.get(logKey, 'json');
    if (!Array.isArray(log) || log.length === 0) return { pushed: 0, skipped: 'never-pushed' };

    const message = formatResultMessage(record, winLoss, exitPrice);
    const results = await Promise.allSettled(
      log.map(entry => sendTelegramMessage(entry.chatId, message, env)),
    );
    const delivered = results.filter(r => r.status === 'fulfilled').length;

    // One result per signal — drop the log so a re-resolve cannot double-notify.
    await env.SIGNAL_CACHE.delete(logKey).catch(() => {});

    console.log('Phase 10 result push: ' + record.id + ' ' + winLoss
      + ' -> ' + delivered + '/' + log.length);
    return { pushed: delivered };
  } catch (e) {
    console.warn('pushResultToSubscribers error: ' + e.message);
    return { pushed: 0, error: e.message };
  }
}

// ── message formatting ─────────────────────────────────────────────────
export function formatSignalMessage(signal, opts = {}) {
  const sig = signal.signal;
  const dir = sig.finalSignal;
  const emoji = dir === 'BUY' ? '🟢' : '🔴';
  const idShort = String(signal.id || '').slice(-4);
  const bestTF = (sig.bestTimeframe && sig.bestTimeframe.timeframe) || '5min';
  const rec = (sig.recommendations && sig.recommendations[bestTF]) || {};
  const entry = rec.entry && rec.entry.price;
  const isFx = opts.fx === true || sig.mode === 'fx';
  const isBoth = opts.fx === true && opts.fxOnly !== true;
  const levels = sig.fxLevels || null;
  const expMin = rec.expiry && rec.expiry.totalMinutes;
  const countdown = rec.expiry && rec.expiry.countdown && rec.expiry.countdown.label;
  const grade = (sig.grade && sig.grade.grade) || '';
  const label = (sig.grade && sig.grade.label) || '';
  const confNum = parseInt(String(sig.confidence || '0%').replace('%', '')) || 0;
  const filled = Math.round(confNum / 10);
  const bar = '█'.repeat(filled) + '░'.repeat(10 - filled);
  const barEmoji = confNum >= 85 ? '🟢' : confNum >= 70 ? '🟡' : '🔴';
  const sv = sig.structureVerdict;

  const lines = [];
  lines.push('📌 Signal No. ' + idShort);
  lines.push('📊 ' + signal.pair + ' | ' + bestTF + (isFx ? (isBoth ? ' | 🔄 BOTH' : ' | 💹 FX') : ' | ⏱ FTT'));
  lines.push('━━━━━━━━━━━━━━');
  lines.push(emoji + ' ' + dir + '  ' + (sig.confidence || '') + '  ' + (grade + ' ' + label).trim());
  lines.push(barEmoji + ' ' + bar);
  if (entry != null) lines.push('💰 Entry: ' + entry);
  if (isFx && levels && levels.sl && levels.tp) {
    lines.push('🛑 SL: ' + levels.sl);
    lines.push('🎯 TP: ' + levels.tp + '  (1:' + (levels.rr || '2.5') + ')');
  }
  if (isFx && opts.fxOnly === true) {
    // pure FX: no fixed expiry lines
  } else {
    if (expMin != null) lines.push('⏰ Expiry: ' + expMin + ' min');
    if (countdown) lines.push('🕐 Candle closes: ' + countdown);
  }
  if (sig.higherTFTrend) lines.push('📈 HTF: ' + sig.higherTFTrend);
  if (sig.marketRegime) lines.push('🟡 Regime: ' + sig.marketRegime);
  if (sig.regimeAdvice) lines.push('💡 ' + sig.regimeAdvice);
  if (sv && sv.overall && sv.overall !== 'N/A') {
    const sE = sv.overall === 'ALIGNED' ? '✅' : sv.overall === 'AGAINST' ? '⚠️' : sv.overall === 'MIXED' ? '🔀' : '➡️';
    let sLine = sE + ' Structure: ' + sv.overall;
    if (sv.direction && sv.direction !== 'NEUTRAL') sLine += ' (' + sv.direction + ' ' + (sv.strength || '') + ')';
    lines.push(sLine);
  }
  if (sig.entryReason) { lines.push(''); lines.push('📝 ' + sig.entryReason); }
  lines.push('');
  lines.push('⏳ Result will be tracked automatically');
  lines.push('⚡ Live push · fresh generation');
  return lines.join('\n');
}

export function formatResultMessage(record, winLoss, exitPrice) {
  const emoji = winLoss === 'WIN' ? '🏆' : '❌';
  const idShort = String(record.id || '').slice(-4);
  const entry = record.entryPrice;
  const dir = record.direction;

  let deltaStr = 'N/A';
  if (exitPrice != null && entry != null && isFinite(exitPrice) && isFinite(entry)) {
    const delta = dir === 'BUY' ? exitPrice - entry : entry - exitPrice;
    // Crypto moves in whole units, forex in 5th-decimal pips — pick a sane
    // precision instead of printing 0.0000 for a real BTC move.
    const digits = Math.abs(entry) >= 100 ? 2 : 5;
    deltaStr = (delta >= 0 ? '+' : '') + delta.toFixed(digits);
  }

  return [
    '🎯 Result: ' + winLoss + ' ' + emoji,
    '',
    '📌 Signal No. ' + idShort,
    '📊 ' + record.pair + ' · ' + dir,
    'Entry: ' + (entry != null ? entry : '?') + ' → Exit: ' + (exitPrice != null ? exitPrice : '?'),
    'Δ: ' + deltaStr,
  ].join('\n');
}

/**
 * Plain-text sendMessage. No parse_mode on purpose — see the header note and
 * the Bot's own Bug#1 comment.
 */
export async function sendTelegramMessage(chatId, text, env) {
  const token = botToken(env);
  const url = TELEGRAM_API + '/bot' + token + '/sendMessage';
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chat_id: chatId,
      text: String(text || ''),
      disable_web_page_preview: true,
    }),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    console.warn('Telegram sendMessage failed: chatId=' + chatId
      + ' status=' + res.status + ' body=' + body.slice(0, 200));
    throw new Error('Telegram ' + res.status + (body ? ' ' + body.slice(0, 120) : ''));
  }
  return res.json().catch(() => ({}));
}

export async function validateBotToken(env) {
  if (!botToken(env)) return { ok: false, reason: 'missing', checkedAt: new Date().toISOString() };
  if (env.SIGNAL_CACHE) {
    try {
      const cached = await env.SIGNAL_CACHE.get(TOKEN_CHECK_KEY, 'json');
      if (cached && cached.checkedAt
          && (Date.now() - new Date(cached.checkedAt).getTime()) < TOKEN_CHECK_TTL_S * 1000) {
        return cached;
      }
    } catch (e) { /* fall through */ }
  }
  try {
    const res = await fetch(TELEGRAM_API + '/bot' + botToken(env) + '/getMe', {
      signal: AbortSignal.timeout(5000),
    });
    const body = await res.json().catch(() => ({}));
    const result = (res.ok && body.ok)
      ? { ok: true, reason: null, username: body.result && body.result.username, checkedAt: new Date().toISOString() }
      : {
          ok: false, reason: 'invalid', status: res.status,
          description: body.description || null, checkedAt: new Date().toISOString(),
        };
    if (env.SIGNAL_CACHE) {
      await env.SIGNAL_CACHE.put(TOKEN_CHECK_KEY, JSON.stringify(result), {
        expirationTtl: TOKEN_CHECK_TTL_S,
      }).catch(() => {});
    }
    return result;
  } catch (e) {
    return { ok: false, reason: 'error', error: e.message, checkedAt: new Date().toISOString() };
  }
}

export async function getSubscriberSnapshot(env) {
  const out = [];
  if (!env || !env.BOT_KV) return out;
  let autoUsers;
  try { autoUsers = await env.BOT_KV.get('auto_users', 'json'); }
  catch (e) { return [{ error: e.message }]; }
  for (const cid of normalizeAutoUsers(autoUsers)) {
    try {
      const user = await env.BOT_KV.get('u:' + cid, 'json');
      out.push({
        chatId: String(cid),
        found: !!user,
        autoEnabled: isAutoEnabled(user),
        pair: user && user.pair || null,
        watchlist: user && Array.isArray(user.watchlist) ? user.watchlist : [],
        gradeFilter: (user && user.gradeFilter) || 'ALL',
        minConfidence: (user && user.minConfidence) || 0,
        aiOnlyMode: !!(user && user.aiOnlyMode),
        fxMode: (user && user.fxMode) || 'ftt',
      });
    } catch (e) {
      out.push({ chatId: String(cid), found: false, error: e.message });
    }
  }
  return out;
}

export async function getPushStats(env, opts = {}) {
  const token = botToken(env);
  const enabled = !!token;
  const stats = {
    pushEnabled: enabled,
    botKvBound: !!(env && env.BOT_KV),
    noTokenReason: enabled ? null : (env && env.BOT_TOKEN ? 'empty' : 'missing'),
    tokenValid: null,
    tokenUsername: null,
    pushesLast24h: null,
    pushLogsOpen: null,
    subscriberCount: null,
    subscribers: [],
    lastAttempt: null,
  };
  if (!env || !env.SIGNAL_CACHE) {
    if (env && env.BOT_KV) {
      try {
        const autoUsers = await env.BOT_KV.get('auto_users', 'json');
        const ids = normalizeAutoUsers(autoUsers);
        stats.subscriberCount = ids.length;
        stats.subscribers = await getSubscriberSnapshot(env);
      } catch (e) { /* leave null */ }
    }
    return stats;
  }

  try {
    const list = await env.SIGNAL_CACHE.list({ prefix: PUSH_LOG_PREFIX });
    stats.pushLogsOpen = ((list && list.keys) || []).length;
  } catch (e) { /* leave null */ }

  try {
    const arr = await env.SIGNAL_CACHE.get(DELIVERED_24H_KEY, 'json');
    if (Array.isArray(arr)) {
      const now = Date.now();
      stats.pushesLast24h = arr.filter(x => x && x.at && (now - new Date(x.at).getTime()) < 24 * 3600 * 1000)
        .reduce((n, x) => n + (x.n || 1), 0);
    } else {
      stats.pushesLast24h = stats.pushLogsOpen;
    }
  } catch (e) {
    stats.pushesLast24h = stats.pushLogsOpen;
  }

  try {
    stats.lastAttempt = await env.SIGNAL_CACHE.get(LAST_ATTEMPT_KEY, 'json');
  } catch (e) { /* leave null */ }

  if (env.BOT_KV) {
    try {
      const autoUsers = await env.BOT_KV.get('auto_users', 'json');
      const ids = normalizeAutoUsers(autoUsers);
      stats.subscriberCount = ids.length;
      stats.subscribers = await getSubscriberSnapshot(env);
    } catch (e) { /* leave null */ }
  }

  if (opts.validateToken && enabled) {
    const probe = await validateBotToken(env);
    stats.tokenValid = !!probe.ok;
    stats.tokenUsername = probe.username || null;
    if (!probe.ok) stats.noTokenReason = probe.reason || 'invalid';
  }

  return stats;
}

export const __pushTest = {
  normPair, confPct, claimPushLock, releasePushLock, lockKey,
  recordPushAttempt, recordDelivery, botToken,
  PUSH_LOG_PREFIX, PUSH_LOCK_PREFIX, PUSH_LOCK_TTL_S, PUSH_LOG_TTL_S,
  LAST_ATTEMPT_KEY, DELIVERED_24H_KEY, TOKEN_CHECK_KEY,
};
