// D4 v2.1 AVOIDANCE GATE — auto-generated by scripts/d4_v21_avoidance.py
// Phase F analysis artifact. Deterministic, no deps.
// STATUS: NOT CERTIFIED.
//   insufficient data — 0 indicator-complete rows in snapshot (run 2026-08-10T13:23:22Z); pipeline armed, awaiting accumulation
// d4v21Avoid() is a SAFE PASS-THROUGH (gates nothing) until a certified
// run regenerates this file. Do NOT hand-edit CERTIFIED to true.
export const D4V21_GATE = Object.freeze({
  CERTIFIED: false,
  REASON: "insufficient data \u2014 0 indicator-complete rows in snapshot (run 2026-08-10T13:23:22Z); pipeline armed, awaiting accumulat",
});

const _NUM = (v) => {
  if (typeof v === 'number' && isFinite(v)) return v;
  if (typeof v === 'string') { const f = parseFloat(v.replace('%','')); return isFinite(f) ? f : null; }
  return null;
};
const CRYPTO = ['BTC','ETH','SOL','DOGE','XRP','ADA','LINK','AVAX','BNB','DOT'];
function _features(s) {
  const ind = Object.assign({}, s.edge || {}, s.signalIndicators || {});
  const ts = s.timestamp || '';
  const pair = s.pair || '?';
  const rsi = _NUM(ind.rsi);
  const dir = s.direction;
  const g = s.grade;
  const sv = s.structureVerdict;
  let dow = null, hour = null;
  try { hour = parseInt(ts.slice(11, 13), 10); if (isNaN(hour)) hour = null; } catch (e) {}
  try { dow = new Date(ts.slice(0, 10) + 'T00:00:00Z').getUTCDay(); if (isNaN(dow)) dow = null; dow = (dow + 6) % 7; } catch (e) {}
  return {
    pair: pair,
    assetType: s.isOTC ? 'OTC' : (CRYPTO.some(t => pair.includes(t)) ? 'CRYPTO' : 'FOREX'),
    direction: dir,
    bestTF: s.bestTF || (typeof ind.bestTF === 'string' ? ind.bestTF : null),
    marketRegime: s.marketRegime || null,
    sessionQuality: s.sessionQuality || null,
    grade: (g && typeof g === 'object') ? g.grade : (g || null),
    alignment: s.alignment || null,
    structureVerdict: (sv && typeof sv === 'object') ? sv.overall : (sv || null),
    confidence: _NUM(s.confidence),
    coreConfidence: _NUM(s.coreConfidence),
    hour: hour, dow: dow,
    "rsi": _NUM(ind["rsi"]),
    "atrPct": _NUM(ind["atrPct"]),
    "adx": _NUM(ind["adx"]),
    "bbBandwidth": _NUM(ind["bbBandwidth"]),
    "hourMult": _NUM(ind["hourMult"]),
    "sessionRange": _NUM(ind["sessionRange"]),
    "sessionRangeMult": _NUM(ind["sessionRangeMult"]),
    "atrPercentile": _NUM(ind["atrPercentile"]),
    "volMult": _NUM(ind["volMult"]),
    "atrMult": _NUM(ind["atrMult"]),
    "recentFormWr": _NUM(ind["recentFormWr"]),
    "recentFormMult": _NUM(ind["recentFormMult"]),
    "totalMult": _NUM(ind["totalMult"]),
    bbState: ind.bbState != null ? String(ind.bbState) : null,
    rsiChase: (rsi != null && (dir === 'BUY' || dir === 'SELL'))
      ? (((dir === 'BUY' && rsi > 55) || (dir === 'SELL' && rsi < 45)) ? 'CHASE' : 'OK')
      : null,
  };
}

export function d4v21Avoid(signal) {
  void signal;
  return { trade: true, pWin: null, certified: false, gated: false };
}
