#!/data/data/com.termux/files/usr/bin/bash
# ─────────────────────────────────────────────────────────────
# FTT daily: snapshot → analysis → report → push to cloud workspace
# Use:  cd ~/ftt-workspace && bash daily-push.sh
# ─────────────────────────────────────────────────────────────
set -u
cd "$(dirname "$0")"

echo "=== [1/4] Fresh snapshot ==="
if [ -f scripts/phase_f_snapshot.sh ]; then
  bash scripts/phase_f_snapshot.sh 2>&1 | tail -3
else
  bash ~/phase_f_snapshot.sh 2>&1 | tail -3
fi
TODAY=$(date -u +%F)

echo "=== [2/4] Archive data ==="
mkdir -p data
# snapshot folder workspace root-e ase (phase_f_forward/) — tar koro
if [ -d phase_f_forward ]; then
  tar -czf "data/phase_f_forward_${TODAY}.tar.gz" phase_f_forward/
  echo "  → data/phase_f_forward_${TODAY}.tar.gz ($(du -h data/phase_f_forward_${TODAY}.tar.gz | cut -f1))"
fi

echo "=== [3/4] Generate report ==="
REPORT="reports/PHASE_F_${TODAY}.md"
{
  echo "# PHASE F — ${TODAY}"
  echo ""
  echo "Snapshot: \`phase_f_forward/${TODAY}/\` (18 pairs, http=200)"
  echo ""
  echo "\`\`\`"
  python3 scripts/entryhit_corrected_analysis.py 2>/dev/null | head -12
  python3 scripts/day3_analysis.py 2>/dev/null | grep -E "===|^20[0-9]{2}-" | head -8
  echo "\`\`\`"
  echo ""
  echo "_Auto-generated by daily-push.sh — run analysis scripts for full detail._"
} > "$REPORT"
echo "  → $REPORT"

echo "=== [4/4] Commit + push ==="
git add -A 2>/dev/null
if git diff --cached --quiet 2>/dev/null; then
  echo "  nothing to commit"
else
  git -c user.name="ftt-daily" -c user.email="ftt@local" commit -m "daily ${TODAY}: snapshot + report" 2>&1 | tail -1
  git push 2>&1 | tail -2
fi
echo "✅ Done — cloud workspace updated: https://github.com/<tumi>/ftt-workspace"
