#!/data/data/com.termux/files/usr/bin/bash
# ─────────────────────────────────────────────────────────────
# FTT daily: snapshot → analysis → report → push to cloud workspace
# Use:  cd ~/Workplace-drive- && bash scripts/daily-push.sh
# ─────────────────────────────────────────────────────────────
set -u

# Resolve to repo root (scripts/ এর parent)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

echo "=== [1/4] Fresh snapshot ==="
if [ -f "$SCRIPT_DIR/phase_f_snapshot.sh" ]; then
  bash "$SCRIPT_DIR/phase_f_snapshot.sh" 2>&1 | tail -3
elif [ -f ~/phase_f_snapshot.sh ]; then
  bash ~/phase_f_snapshot.sh 2>&1 | tail -3
else
  echo "  ⚠️ phase_f_snapshot.sh not found — skipping snapshot"
  echo "  Run: bash scripts/phase_f_snapshot.sh  (from drive repo)"
fi
TODAY=$(date -u +%F)

echo "=== [2/4] Archive data ==="
mkdir -p data
# snapshot folder ~/phase_f_forward/ — tar into repo data/
SNAP_DIR="$HOME/phase_f_forward"
if [ -d "$SNAP_DIR" ]; then
  tar -czf "data/phase_f_forward_${TODAY}.tar.gz" -C "$HOME" phase_f_forward/
  echo "  → data/phase_f_forward_${TODAY}.tar.gz ($(du -h "data/phase_f_forward_${TODAY}.tar.gz" | cut -f1))"
else
  echo "  ⚠️ $SNAP_DIR not found — no data to archive"
fi

echo "=== [3/4] Generate report ==="
mkdir -p reports
REPORT="reports/PHASE_F_${TODAY}.md"
{
  echo "# PHASE F — ${TODAY}"
  echo ""
  echo "Snapshot: \`phase_f_forward/${TODAY}/\` (18 pairs, http=200)"
  echo ""
  echo "\`\`\`"
  python3 "$SCRIPT_DIR/entryhit_corrected_analysis.py" 2>/dev/null | head -12
  python3 "$SCRIPT_DIR/day3_analysis.py" 2>/dev/null | grep -E "===|^20[0-9]{2}-" | head -8
  echo "\`\`\`"
  echo ""
  echo "_Auto-generated by daily-push.sh — run analysis scripts for full detail._"
} > "$REPORT"
echo "  → $REPORT"

echo "=== [4/4] Commit + push ==="
git add -A 2>/dev/null
if git diff --cached --quiet 2>/dev/null; then
  echo "  nothing to commit"
else
  git -c user.name="ftt-daily" -c user.email="ftt@local" commit -m "daily ${TODAY}: snapshot + report" 2>&1 | tail -1
  git push 2>&1 | tail -2
fi
echo "✅ Done — cloud workspace updated"
